# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='app_users', to='accounts.Account'),
        ),
    ]
