# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170211_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acctid',
            field=models.CharField(default=123, max_length=254),
            preserve_default=False,
        ),
    ]
