# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=254)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DebtBudget',
            fields=[
                ('budget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgets.Budget')),
                ('total_owed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=254)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('budgets.budget',),
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('budget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgets.Budget')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=254)),
            ],
            bases=('budgets.budget',),
        ),
        migrations.CreateModel(
            name='SavingsBudget',
            fields=[
                ('budget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgets.Budget')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('goal_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=254)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            bases=('budgets.budget',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budgets.Budget'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='budgets.Tag'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.AppUser'),
        ),
    ]
