# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('budget_type', models.CharField(choices=[('expense', 'Expense'), ('savings', 'Savings'), ('debt', 'Debt')], max_length=254)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('goal_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('period', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=254, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.TextField(default="<i class='fa fa-cube' aria-hidden='true'></i>")),
            ],
        ),
        migrations.CreateModel(
            name='BudgetThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_through_models', to='budgets.Budget')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('value', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=254)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.Account')),
                ('budgets', models.ManyToManyField(blank=True, through='budgets.BudgetThroughModel', to='budgets.Budget')),
                ('tags', models.ManyToManyField(blank=True, to='budgets.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='budgetthroughmodel',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_through_models', to='budgets.Transaction'),
        ),
        migrations.AddField(
            model_name='budget',
            name='icon_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.Color'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.AppUser'),
        ),
    ]
