# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-02 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
