# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='icon_color',
            field=models.CharField(default='#4b4d4c', max_length=254),
        ),
    ]
