# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='icon',
            field=models.TextField(default="<i class='fa fa-cube' style='font-size: 4em;' aria-hidden='true'></i>"),
        ),
    ]
