# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='icon',
            field=models.TextField(default="<i class='fa fa-cube' aria-hidden='true'></i>"),
        ),
    ]
